# .streamlit/config.toml

[server]
headless = true
enableCORS = false
port = 8501

[logger]
# Level can be "error", "warning", "info", or "debug".
# "debug" is very verbose and useful for diagnosing issues.
level = "debug"